/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gradlelab

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class RecordstrPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        val extension = project.extensions.create("recordstr", RecordstrExtension::class.java)
        extension.str.convention("hello world!")
        extension.helloFile.convention(project.layout.buildDirectory.file("hello.txt"))

        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'com.gradlelab.recordstr'")
            }
        }
    }
}
